USE TechStation;
-- Creation script file

CREATE TABLE STORE (
Store_CODE    INTEGER   NOT NULL  UNIQUE,
Store_ADDRESS  VARCHAR(100)   NOT NULL,
PRIMARY KEY(Store_CODE)
) ;
INSERT INTO STORE
VALUES (88088,'20 Fake Avenue,Springfield,NY 08824');

CREATE TABLE JOB (
Job_CODE  		INTEGER		NOT NULL UNIQUE,
Job_DISCRIP		VARCHAR(100)  NOT NULL,
Job_TYPE		VARCHAR(15) NOT NULL,
PRIMARY KEY(Job_CODE)
);

CREATE TABLE EMPLOYEE (
EMP_NUM 	INTEGER		NOT NULL UNIQUE,
EMP_LNAME	CHAR(15)	NOT NUll,
EMP_FNAME 	CHAR(15)	NOT NULL,
EMP_ADDRESS	VARCHAR(25)	NOT NULL,
EMP_SALARY CHAR(10) 	NOT NULL,
PRIMARY KEY(EMP_NUM)
);
ALTER TABLE EMPLOYEE AUTO_INCREMENT =1;
ALTER TABLE EMPLOYEE ALTER EMP_NUM SET DEFAULT 100;

-- Creation of child classess Sales Associate, whose parent class is Employee
CREATE TABLE SALES_ASSOCIATE (
EMP_NUM INTEGER,
Valid_DL VARCHAR(5),
DL_STATE VARCHAR(2),
PRIMARY KEY(EMP_NUM)
);
ALTER TABLE SALES_ASSOCIATE
ADD CONSTRAINT FK_CHILD FOREIGN KEY(EMP_NUM) REFERENCES EMPLOYEE(EMP_NUM);

-- Creation of child classess Sales Associate, whose parent class is Employee
CREATE TABLE MANAGER (
EMP_NUM INTEGER,
MAN_CERT VARCHAR(20),
MAN_TITLE VARCHAR(20),
PRIMARY KEY(EMP_NUM)
);
ALTER TABLE MANAGER
ADD CONSTRAINT FK2_CHILD FOREIGN KEY(EMP_NUM) REFERENCES EMPLOYEE(EMP_NUM);


CREATE TABLE CUSTOMER (
CUS_ID		INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
CUS_FNAME	CHAR(15) 	NOT NULL,
CUS_LNAME	CHAR(15)	NOT NULL,
CUS_DOB		DATE,
CUS_ADDRESS	VARCHAR(100) NOT NULL,
PRIMARY KEY(CUS_ID)
);
ALTER TABLE CUSTOMER
AUTO_INCREMENT = 9001;



-- ALTER TABLE SUPPLIER
-- ADD CONSTRAINT Sup_A UNIQUE (Sup_AMOUNT);
-- ALTER TABLE SUPPLIER
-- ADD Sup_PRICE INTEGER;
-- CREATE TABLE SUPPLIER (
-- Sup_DATE	date	NOT NULL,
-- Sup_VENDOR	CHAR(10)	NOT NULL,
-- Sup_AMOUNT	INTEGER		NOT NULL,
-- PRIMARY KEY(Sup_DATE)
-- );
-- ALTER TABLE SUPPLIER
-- ADD Sup_ITEM VARCHAR(15),
-- ADD Sup_CODE INTEGER NOT NULL;

-- Supplier Table Creation
CREATE TABLE SUPPLIER (
Sup_CODE INTEGER UNIQUE AUTO_INCREMENT,
Sup_VENDOR VARCHAR(20),
Sup_ITEM VARCHAR(50),
Sup_AMOUNT INTEGER NOT NULL, -- Replaced with Sup_STOCK
Sup_DATE DATE NOT NULL,
PRIMARY KEY(Sup_CODE)
);

ALTER TABLE SUPPLIER
AUTO_INCREMENT = 825;

ALTER TABLE SUPPLIER
ADD Sup_PRICE INTEGER NOT NULL;
ALTER TABLE SUPPLIER
ADD Sup_STOCK INTEGER NOT NULL;




-- ALTER TABLE ITEM
-- ADD Item_PRICE INTEGER NOT NULL;
-- CREATE TABLE ITEM (
-- Item_SKU INTEGER NOT NULL UNIQUE,
-- Item_DISCRIP VARCHAR(50),
-- Sup_DATE DATE NOT NULL,
-- Sup_AMOUNT INTEGER NOT NULL,
-- PRIMARY KEY(Item_SKU),
-- FOREIGN KEY(Sup_DATE) REFERENCES SUPPLIER(Sup_DATE) ON UPDATE CASCADE,
-- FOREIGN KEY(Sup_AMOUNT) REFERENCES SUPPLIER(Sup_AMOUNT) ON UPDATE CASCADE
-- );
-- ALTER TABLE ITEM
-- DROP FOREIGN KEY ITEM_ibfk_1;
-- ALTER TABLE ITEM
-- DROP FOREIGN KEY ITEM_ibfk_2;

-- ALTER TABLE ITEM
-- ADD FOREIGN KEY(Sup_DATE) REFERENCES SUPPLIER(Sup_DATE);

-- ALTER TABLE ITEM
-- ADD FOREIGN KEY(Sup_AMOUNT) REFERENCES SUPPLIER(Sup_AMOUNT);

-- ITEM Table Creation
CREATE TABLE ITEM (
Item_CODE INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
Item_NAME VARCHAR(50),
Item_PRICE INTEGER NOT NULL,
Item_STOCK INTEGER NOT NULL,
PRIMARY KEY(Item_CODE)
);
ALTER TABLE ITEM AUTO_INCREMENT = 6060;
-- Creation of child GAME, whose parent class is ITEM
CREATE TABLE GAME (
Item_CODE INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
G_Platform VARCHAR(50),
PRIMARY KEY(Item_CODE),
FOREIGN KEY(Item_CODE) REFERENCES ITEM(Item_CODE)
);
/*ALTER TABLE ITEM
ADD CONSTRAINT FK3_CHILD FOREIGN KEY(Item_CODE) REFERENCES ITEM(Item_CODE);*/

-- Creation of child MOVIE, whose parent class is ITEM

CREATE TABLE MOVIE (
Item_CODE INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
Movie_SCORE INTEGER,
PRIMARY KEY(Item_CODE),
FOREIGN KEY(Item_CODE) REFERENCES ITEM(Item_CODE)
);
/*ALTER TABLE MOVIE
ADD CONSTRAINT FK4_CHILD FOREIGN KEY(Item_SKU) REFERENCES ITEM(Item_SKU);*/




CREATE TABLE RECEIPT (
Receipt_NUM INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
CUS_ID INTEGER NOT NULL UNIQUE,
Sold_ITEM VARCHAR(50) NOT NULL,
Sold_PRICE INTEGER NOT NULL,
Receipt_DATE DATE NOT NULL,
PRIMARY KEY(Receipt_NUM)
);

ALTER TABLE RECEIPT AUTO_INCREMENT = 8850000;
ALter Table RECEIPT
ADD Sold_QTY INTEGER NOT NULL;









