USE TechStation;
SHOW CREATE TABLE ITEM;
SHOW CREATE TABLE GAME;
SHOW CREATE TABLE MOVIE;

SELECT EMPLOYEE.EMP_NUM
FROM EMPLOYEE
FULL OUTER JOIN MANAGER 
ON EMPLOYEE.EMP_NUM=MANAGER.EMP_NUM;

-- Drop SUPPLIER TABLE,ITEM TABLE AND CHILD TABLES
DROP TABLE GAME;
DROP TABLE MOVIE;
DROP TABLE ITEM;
DROP TABLE SUPPLIER;

SELECT Sup_CODE, Sup_VENDOR, Sup_ITEM, Sup_DATE, Sup_PRICE AS Item_Price, Sup_STOCK
FROM SUPPLIER
ORDER BY SUP_PRICE DESC;

SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_SALARY AS PAID_MOST
FROM EMPLOYEE
WHERE EMP_SALARY = '$50,000';
