USE TechStation;
-- Insertion script file

-- Employee data insertion
INSERT INTO EMPLOYEE(EMP_FNAME,EMP_LNAME,EMP_ADDRESS,EMP_SALARY)
VALUES ('John','Smith','80 Vent Rd,Unknown,NY,11111','$40,000');
INSERT INTO EMPLOYEE(EMP_NUM,EMP_FNAME,EMP_LNAME,EMP_ADDRESS,EMP_SALARY)
VALUES (101,'Ben','Van','90 kent Rd,Udad,NY,10000','$50,000');

-- DELETE FROM EMPLOYEE WHERE EMP_NUM = 100;

-- Child SALES_ASSOCIATE Data Insertion
INSERT INTO SALES_ASSOCIATE(EMP_NUM, Valid_DL, DL_STATE)
VALUES (100,'S0123','NY');

-- Child MANAGER Data Insertion
INSERT INTO MANAGER(EMP_NUM, MAN_CERT, MAN_TITLE)
VALUES (101,'PM Certififcation','Project Manager');

-- Job data insertion
INSERT INTO JOB(Job_CODE,Job_DISCRIP,Job_TYPE)
VALUES (1044,'Sales Associate','SA');
INSERT INTO JOB(Job_CODE,Job_DISCRIP,Job_TYPE)
VALUES (2023,'Project Manager','PM');

-- Supplier Data Insertion

INSERT INTO SUPPLIER(Sup_VENDOR, Sup_ITEM,Sup_DATE, Sup_PRICE,Sup_STOCK)
VALUES ('AMAZON','Sonic Generations','2020-10-12',25, 40);
INSERT INTO SUPPLIER(Sup_VENDOR, Sup_ITEM,Sup_DATE, Sup_PRICE,Sup_STOCK)
VALUES ('AMAZON','Sonic The Hedgehog','2020-10-24',10, 15);


 -- DELETE FROM SUPPLIER WHERE Sup_DATE = 0000-00-00;
 
 -- Customer Data Insertion
 INSERT INTO CUSTOMER(CUS_FNAME, CUS_LNAME, CUS_DOB, CUS_ADDRESS)
 VALUES ('Geralt','Rivia','1215-12-25','200 Velen Ave,Velen,NY,02101');
 INSERT INTO CUSTOMER(CUS_FNAME, CUS_LNAME, CUS_DOB, CUS_ADDRESS)
 VALUES ('Nathan','Drake','1976-01-01','400 Amongthieves St,EL Dorado,NY,42141');
 
 -- ITEM Data Insertion
INSERT INTO ITEM(Item_NAME, Item_PRICE, Item_STOCK) 
VALUES ('Sonic Generations',30,40);
INSERT INTO ITEM(Item_NAME, Item_PRICE, Item_STOCK)
VALUES ('Sonic The Hedgehog',13,15);


-- GAME Data Insertion
INSERT INTO GAME(Item_CODE, G_Platform)
VALUES (6060,'PS3,XBOX 360,PC');

-- MOVIE Data Insertion
INSERT INTO MOVIE(Item_CODE, Movie_SCORE)
VALUES (6061,63);

-- RECEIPT Data Insertion
INSERT INTO RECEIPT(CUS_ID)
SELECT CUS_ID FROM CUSTOMER;

INSERT INTO RECEIPT(Sold_ITEM,Sold_PRICE,Receipt_DATE,Sold_QTY)
VALUES ('Sonic Generations', '30', '2020-11-05',1);
UPDATE RECEIPT
SET CUS_ID = 9001
WHERE CUS_ID = 0;

